### ISSUE TITLE
[RFE] represent large numbers with readable format instead of exponents

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#122]
# Description
To avoid overflow on chart axis, the PR https://github.com/RedHatInsights/tower-analytics-frontend/pull/121 displays the savings in a readable format (millions/billions etc).

It would be great to have a similar behavior in rest of the places:

- [ ] Total savings
- [ ] Individual savings in top template section
- [ ] cost/savings in the chart tooltip

**Mock up**

Add mock up here when ready

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by kialam** [comment]
The adjustments for the chart axis was to avoid unwanted overflow, however for cost savings I think we would want to leave the monetary amount as it is so that users know how much they're saving. When you start adjusting things by decimal point rounding, specific amounts become lost, e.g. `$3823.23` becomes `$3.8k`.

**Comment by kialam** [comment]
Closing as "won't do".
