### ISSUE TITLE
Automation Calculator does not handle the no-data code correctly

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#160]
**Describe the bug**

Automation Calculator does not handle the no-data code correctly.  It should catch the no-data code from the API and switch to the no-data page instead of letting the error be uncaught.

**To Reproduce**
1. Go to /beta/ansible/automation-analytics/automation-calculator with a user with no database
2. Check the console for errors

**Expected behavior**

The no-data page should be shown like the other pages do.

**Comment by jctanner** [comment]
@benthomasson can you elaborate on what setup you used to arrive at this bug? Following https://tannerjc.net/wiki/index.php?title=Automation_Analytics#fullstack_dev_setup and visiting https://ci.foo.redhat.com:1337/ansible/automation-analytics/automation-calculator with rhn-support-jtanner, I do see the "no data found" page.

![image](https://user-images.githubusercontent.com/1869705/86014941-fad77280-b9ee-11ea-9f89-4882f9218903.png)

**Comment by benthomasson** [comment]
It was found in sentry reports.   @unlikelyzero might be able to help extract some better information from sentry than I have been able to.

**Comment by unlikelyzero** [comment]
@jctanner this may be easiest to reproduce in prod when using a user without sufficient privileges to view automation calculator

**Comment by jctanner** [comment]
with some guidance from @benthomasson and @appuk, I did the following ...

1. commented out the frontend from local.yml
2. spun up the backend with `make up`
3. ran `make init`
4. spun up the frontend with `npm run start:container`
5. set the frontend IP to the gateway inside the proxy container
6. opened https://prod.foo.redhat.com:1337 to verify i saw data
7. connected to postgres, dropped tenant_1 and deleted all tenant ids
8. re-opened https://prod.foo.redhat.com:1337

All pages are showing the "no data" message properly. This bug is ready to close I think, so setting it to "needs_test".

**Comment by appuk** [comment]
@jctanner I still see 404s on all apis when there is no data for the user
![image](https://user-images.githubusercontent.com/11617351/92744912-e3eac000-f34f-11ea-86c4-2c55280db9de.png)

cc @unlikelyzero can you clarify what is the expected behavior in this issue?

**Comment by unlikelyzero** [comment]
You should not get the Uncaught (in promise) console error

**Comment by jctanner** [comment]
reopened for testing.

**Comment by appuk** [comment]
Not getting the uncaught console error anymore, hence closing

![Screen Shot 2020-09-23 at 12 12 13 PM](https://user-images.githubusercontent.com/11617351/94039802-28d21600-fd96-11ea-9a46-75a7a19aaabc.png)
