### ISSUE TITLE
Job Detail Page

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/tower-analytics-frontend#225]
# Description

This issue captures all the ideas for what would go on the job detail page.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Mock up**

Add mock up here when ready

**Related PRs**

Add PRs here when ready

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by wenottingham** [comment]
@trahman73 do you have a latest proposed mockup to use as a starting point?

**Comment by trahman73** [comment]
https://tower-mockups.testing.ansible.com/analytics/jobs/analytics-jobs-expand/

**Comment by Ladas** [comment]
I think we could show all of these as dashboard with charts/tables in order of:

[3. workflow topology] (optional, if job is workflow)
[4. template chart]
[5. correlation chart for tasks]
[1. most failed tasks][2. failed hosts]

We can take this as other dashboards, e.g. the 1,2. would be small boxes with `show more` functionality that would lead to explorer pages with all the filtering/ordering options?

------------

1. Following the job list details, we'd have a list of all failed tasks under the job (the expandable job detail just shows max 2)

It's a paginated list of tasks ordered by failed hosts (so most failed tasks). We could make that as default, but we should be able to order by something else, leading to e.g. most skipped tasks, most retried tasks, etc.

And this list could switch to list of modules (later maybe roles, etc.) (if we'd click on group by task/module ?) Showing the same data, e.g. list of most skipped modules


2. Paginated list of hosts (like tower shows in play recap https://github.com/RedHatInsights/tower-analytics-backend/issues/469)

Orderable by task states, so e.g. show me hosts with most skipped tasks. And showing on what task the host failed, if it failed. (e.g. ordering by failed or unreachable states would show up these hosts first)

We should be able to show the host run, so e.g. showing host has 7 skipped tasks, we could click on host and show all the tasks (might need to be still paginated, since we can have workflow with hundreds of tasks)

3. For workflow, we should maybe show the topology? And mark the fatal failure nodes? With counts of how many hosts failed there? (Allowing drilldown)

4. Correlation to other runs. Probably seeing chart with this template successful/failed jobs runs past X days by default. (job explorer filter allowing to filter cluster, orgs, date range, etc. group by cluster/org). 

5. Correlation of task stats for this job/vs template. E.g. seeing avg. elapsed time per day and last point is this job for correlation. Or we could switch whatever by selectbox. E.g. avg. skipped tasks per host, vs. skipped tasks per host in this job.


And probably more. As we get to anomalies/perf recommendations, etc.

**Comment by Ladas** [comment]
Btw. template detail page would be probably very similar (and cluster/org detail page could be similar to a degree)

**Comment by wenottingham** [comment]
> [3. workflow topology] (optional, if job is workflow)
> [4. template chart]
> [5. correlation chart for tasks]
> [1. most failed tasks][2. failed hosts]

1/2. For failed tasks & failed hosts, I think we should do some data analysis to get useful normal case scenarios. My suspicion is that in the majority of  cases, the number of distinct failed tasks is small (assuming fatal failures, and not caught failures), and once you get down to tasks that only failed on one or two hosts, you're more likely to want to view that in the context of the individual hosts it failed on rather than as the list of tasks.

3. Unless this replicates the Tower view, complete with letting you click through each node to view the job for that node, I would not build this in the Analytics UI. At least, not as a first pass.

4 & 5: these seem targeted as details for the *template*, not for the individual job run.

**Comment by Ladas** [comment]
@wenottingham 1/2 these could be tabs maybe?

One is the list of hosts that we get on a bottom of tower job detail, see: https://github.com/RedHatInsights/tower-analytics-backend/issues/469 (but it would paginated filterable list, showing names of unreachable/ failed tasks):
```
host 1 | changed 10 | failed 1 (showing the task failure here, maybe on hover, so e.g. 'configure db' task) | unreachable 0 | ...
host 2 | changed 10 | failed 1 | unreachable 0 | ...
...
```

Other would be list of tasks, with expandable list of hosts? So e.g. list of tasks ordered by total failed count, filtering only failed/unreachable hosts (and I could change the filter to show me e.g. hosts skipping the tasks ordered by most skipped tasks, or by playbook task order):
```
gather facts [10 unreachable hosts]:
[ + show hosts] (leading to paginated list of hosts, looking as above host list)

configure db [2 unreachable hosts, 6 failed hosts]:
[ - show hosts]
- host 1 | changed 10 | failed 1 | unreachable 0 | ...
- host 20 | changed 10 | failed 0 | unreachable 1 | ...

install db [2 unreachable hosts, 5 failed hosts]:
[ + show hosts]
```

@wenottingham we should offer both views, since it depends on how the tasks will be distributed, or what you're looking for. If you have a lot of failures on different tasks, host list filtering only failures might be better. Otherwise grouping hosts by failed task will be easier to go through.


--------

3. Agreed, this would be probably another phase. Was thinking different view than tower though. Rather showing where are you in the nested workflow hierarchy and to observe 1 workflow structure, we could point to tower.

So e.g. workflow W0 having nodes J1, J2, J3, W1, W2, W3 (jobs and workflows nopdes connected somehow), then nested W1 having J11, W11, W12, then W11 having J111, J112

Then I was thinking we'd be showing a navigation, rather than detailed topology.

So e.g. being at W11 I could just see:
```
W0 -> W1 -> [W11] <- this is me!

siblings: [nodes around me, maaaybe the topology of W1 (parent), or just a link to tower to show topology]:
[J11, W11, W12]

children [if active job is a workflow again, maaaybe the topology of W11, or just a link to tower to show topology]:
[J111, J112]
```

AFAIK tower is just showing immediate parent and nodes? But this is probably lower priority, unless we have a customer with a lot of workflow levels. :-)

------

4 & 5 - right, that is why I call it correlation chart. E.g. if I'll go to failing job, it'd be good to a have a quick peek of the context (and I'd go into template detail page for more details)

So e.g. clicking on failing job, I'd immediately see: the template started to fail today and there were already 4 other failures. (and I'd probably go to template detail to e.g. see, that it runs fine on cluster 1,2 and fails only on cluster 3 )

**Comment by wenottingham** [comment]
Re: 1/2, would have to think how having part of the view be all hosts for a task, or all tasks for a host, would work even with pagination when a playbook is across 10k hosts and has 100-1000 tasks. I don't want to go back and hit all the same scaling issues we had with https://docs.ansible.com/ansible-tower/2.2.0/html/userguide/_images/job-details.png.

4&5: maybe some of that is just a tooltip on the template link, and you have real detail when you click to view the template details in the template explorer equivalent?

**Comment by Ladas** [comment]
1/2, maybe we'd just link to host/tasks table and not show expandable paginated session (similar to how we crosslink to job explorer table)

4&5 Yeah that might work, lets see how it'll look in mockup

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-162
