### ISSUE TITLE
Job Explorer view - Custom Date filter

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#264]
# Description

This is a placeholder to discuss whether the Custom Date should persist when we refresh the page or when we change the date filter type(Select a Date range, Select some other Date filter type, and select custom again) 

# Verification

**Screenshot**

Add screenshot of implementation here when implemented

**Steps**

Add verification steps here when ready for QE

**Comment by appuk** [comment]
cc @kialam @jeanetteobr @jctanner @trahman73

**Comment by brumik** [comment]
My bad, wrong reference number ^, the PR is **not** related to this issue

**Comment by benthomasson** [comment]
@kialam @brumik @jeanetteobr Does this depend on storing state in the URL?

**Comment by Ladas** [comment]
@benthomasson I think partially? The refresh page part definitely (then page refresh, hitting back in browser navigation, bookmarking and link sharing should be solved, right ?)

For changing the date from custom to quick and back, I guess it's UX question if it should remember it (it probably shouldn't survive refresh, it should just remember the active option)

@appuk btw. if we'll want to keep both quick_date_range and (start_date, end_date), I'll need to tweak the API, since now if you send all of these, the start_date and end_date takes priority.

**Comment by brumik** [comment]
In the UI we clear right now the `start_date` and `end_date` if the `quick_date_range` is not `custom`. I think the backend is good because we don't want to keep in the URL stuff what we don't use no?

**Comment by Ladas** [comment]
@brumik yeah, it sounds right that the URL will have used values only (unless we'd implement kibana style filters, that you can make active/inactive :-) )

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-172
