### ISSUE TITLE
UXD Audit: Add sort by function to columns

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#280]
# Description
Currently we use PF's `DataList` component to create our tables instead of their `Table` component. In order to add column sorting, we'd have to move our lists over to use the `Table` component.
# Verification
![table_sort_columns](https://user-images.githubusercontent.com/2293210/94038732-d0e6df80-fd94-11ea-8750-9b007d6c148a.png)

@Ladas can we sort by `ID/Name` for jobs or is it one or the other?

**Comment by Ladas** [comment]
@kialam right now we can sort only by the `id` of the `id/name` couple. We can't sort by template, cluster, org, ... names, because of the encryption

@benthomasson @wenottingham so we can sort by encrypted names and we can't search by the names. Are these usecases enough justification to remove the custom encryption we're doing? (e.g. for the multiselect box with many values, not being able to search by name server side will be an issue)

**Comment by wenottingham** [comment]
We can or can't sort by the encrypted names? Because if you can sort by the plaintext while it returns encrypted, you can theoretically run a (extremely expensive and complicated) attack to deduce them.

**Comment by Ladas** [comment]
@wenottingham ha, typo :-) we can't :-)

**Comment by jeanetteobr** [comment]
@Ladas @kialam @wenottingham Wondering if we should put this UXD audit change on the back burner until we switch from DataLists to Tables?

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-177
