### ISSUE TITLE
don't show the "complement" aka all other orgs data when filter applied

### ISSUE THREAD

**Issue by kdelee** [RedHatInsights/tower-analytics-frontend#73]
![Screenshot from 2020-02-18 14-12-28](https://user-images.githubusercontent.com/29239279/74769614-bd045980-5258-11ea-8b7e-1b51510a6023.png)
![Screenshot from 2020-02-18 14-12-18](https://user-images.githubusercontent.com/29239279/74769617-be358680-5258-11ea-8344-5b5d119039fe.png)

when "top 5 orgs" filter applied, this 6th org appears called "complement" w/ id of -1 if you peek in api response. This is supposed to represent all other orgs, but it is unclear what it is due to name as well as making my brain spin because I see 6 orgs on filter that says top 5.

**Comment by kialam** [comment]
In the pie charts we purposefully do not render the complement slice, however we do leave the complement info (renamed as "`Others`") in the legend with its count in relation to the other data. 

For the grouped bar chart, I'm not sure what the best course of action is here for an intuitive UI/UX. I think we would still run into a use case where a user could toggle "Bottom 5" orgs and the grouped bar chart could render a very tall "Others" bar in relation to the bottom 5 orgs with the least amount of runs, thus making the chart difficult to read. If that's the case then we should just not render that piece of data in the grouped bar chart at all (e.g. remove from graph and legend). @benthomasson @wenottingham @kdelee do you guys have thoughts on this? 

Another approach is to set "Others" to deselected in the grouped bar chart. But then we're talking about implementing edge case logic into our code when perhaps what makes the most sense is to not show the "Others" data until we figure out a) if customers want to see this and b) how to present it in an intuitive and non-confusing manner.

**Comment by benthomasson** [comment]
I find complement/others confusing and it breaks the expectation of the top 5 and bottom 5 filters.   We should remove it from the charts and legend of UI or remove from the API if that is cleaner.   @kialam @Ladas

**Comment by wenottingham** [comment]
I think it should not just be named 'complement', which may not make sense to the user.

It's probably simplest to leave it out of the grouped bar chart.

**Comment by kialam** [comment]
Sounds good; I will remove this for the grouped bar chart. Do we want to remove it from the pie charts as well?

**Comment by wenottingham** [comment]
If we're not showing the 'Others' slice when a filter is applied, it shouldn't be in the legend, IMO.

**Comment by Ladas** [comment]
@benthomasson @kialam @wenottingham @kdelee 

So stealing from AWS console UI for cost explorer, they are not showing the `Others` only if you're filtering by orgs.

So e.g. you filter 5 orgs, you just see 5 orgs. You filter 11 orgs, then you see 5 orgs and others are computed from the 6 remaining orgs. I think not showing the `Others` will be bad, since then you're loosing important information here (how big is top5 from a total)

To reduce confusion, the `Others` title should say something like `Rest is 1000 job runs over 110 organizations`. And somewhere on the top right there should be note `Total 115 organizations` (and yeah, ideally a filterable multiselect box for orgs)

Btw, for the pie chart, we should be able to enable/disable entities by clicking on the legend (to be able to browse stuff, when 1 part is too big)

Also I really like how AWS does the multiselect filtering, so you can dril down into orgs you're interested in:

![image](https://user-images.githubusercontent.com/1737058/74919105-628b0a80-53ca-11ea-8211-0d181155ea1c.png)

So going the path of multiselect makes probably more sense than the top5 or bottom5. Also with these kind of charts, we should display max 5-10 entities, so the `all` option is not really usable here?

(these are just my 5 cents into how it's presented in other apps, so it makes sense and we don't have to reinvent this kind of presentation)

**Comment by kdelee** [comment]
We decided that for 1.0.1 we are JUST going to rename `complement` to `Others` to match with the other references, and we will revisit this whole topic in a future release.

**Comment by kdelee** [comment]
verified we did the rename...now deployed to QA/beta
![Screenshot from 2020-02-20 14-30-19](https://user-images.githubusercontent.com/29239279/74971188-a8a59580-53ed-11ea-8c34-51f355ba8666.png)
